# example netlify.toml
[build]
  command = "astro build"
  publish = "dist"

[[redirects]]
  from = "/index.html"
  to = "/about/index.html"
  status = 301

[[redirects]]
  from = "/de/index.html"
  to = "/de/about/index.html"
  status = 301
  