# example netlify.toml
[build]
  command = "astro build"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/about"
  status = 301
  force = true

[[redirects]]
  from = "/de"
  to = "/de/about"
  status = 301
  force = true
  