# example netlify.toml
[build]
  command = "astro build"
  publish = "dist"

[[redirects]]
  from = "/about"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/de"
  to = "/"
  status = 301
  force = true
  